import os

TINK_CLIENT_ID = os.environ["TINK_CLIENT_ID"]
TINK_CLIENT_SECRET = os.environ["TINK_CLIENT_SECRET"]
MONGO_CONNECTION_STRING = os.environ["MONGO_CONNECTION_STRING"]
TINK_BASE_URL = "https://api.tink.com"
SELF_BASE_URL = os.environ["SELF_BASE_URL"]
FLASK_SECRET_KEY = os.environ["FLASK_SECRET_KEY"]