name: Test, coverage, and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]

    - name: Run tests
      run: |
        coverage run -m pytest

    - name: Check coverage
      run: |
        coverage report

    - name: Check isort formatting
      run: |
        isort --check-only --diff --recursive src tests

    - name: Check black formatting
      run: |
        black --check --diff src tests
